on:
  issues:
    types: [closed, reopened]

jobs:
  test:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: closed
        if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
        shell: bash
        run: perl -p -i -e "s/Issues\n/Issues\n\n- ${{ github.event.issue.number }}: ${{ github.event.issue.title }} \n//" CHANGELOG.md
      - name: reopend
        shell: bash
        if: ${{ github.event_name == 'issues' && github.event.action == 'reopened' }}
        run: perl -p -i -e "s/- ${{ github.event.issue.number }}: ${{ github.event.issue.title }} \n//" CHANGELOG.md
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: 'CHANGELOG.md'
    
